name: Build test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test
      - name: Run
        run: |
          cargo run -- examples/aplusb.cpp examples/cplusd.cpp --verbose
          clang++ examples/aplusb.cpp -o aplusb.out --std=c++17 -pedantic -O2
          clang++ examples/cplusd.cpp -o cplusd.out --std=c++17 -pedantic -O2
          cargo run -- aplusb.out cplusd.out --skip-compile --verbose
      - name: Include path
        run: clang++ -E -x c++ - -v < /dev/null
